
FORMAT = cargo fmt -- --check
CLIPPY = cargo clippy -- -D warnings
TEST = cargo test 
TEST_VERBOSE =-- --nocapture

#tests names 
FACTORY_METHOD=factory_method_tests
ABSTRACT_FACTORY_METHOD=abstract_factory_tests
BUILDER_METHOD=builder_method_tests
PROTOTYPE_METHOD=prototype_tests
SINGLETON_METHOD=singleton_tests
# Corre todos los tests
test:
	$(TEST)


format-check:
	$(FORMAT)
	$(CLIPPY)
# Corre un archivo específico: make test-file FILE=creational/Factory/facotry_test.py
test-file:
	$(TEST) $(FILE)

test-factory-method:
	$(TEST) $(FACTORY_METHOD) $(TEST_VERBOSE)

test-abstract-factory-method:
	$(TEST) $(ABSTRACT_FACTORY_METHOD) $(TEST_VERBOSE)

test-builder-method:
	$(TEST) $(BUILDER_METHOD) $(TEST_VERBOSE)

test-prototype-method:
	$(TEST) $(PROTOTYPE_METHOD) $(TEST_VERBOSE)


test-singleton-method:
	$(TEST) $(SINGLETON_METHOD) $(TEST_VERBOSE)